##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8888
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path:
#    context-path: /baseadmin
#基础配置
spring:
  profiles:
    active: ${BASE_ADMIN:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: base-admin
  cache: false
  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/

  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #打印SQL
  jpa:
    show-sql: true

#是否需要输入验证码
captcha:
  enable: false

---
##### dev 配置 #######
spring:
  profiles: dev

  #数据库配置
  datasource:
    url: jdbc:mysql://106.55.158.81:3306/base_admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: false

# 微信支付配置
weixin:
  # 秘钥
  key: SD844716311sd1379919849300000000
  # 商户号
  mch_id: 1534054701
  # 公众账号appid
  wxappid: wx32c00b85e0400952
#  wxappid: wxe391560158d7a624
  # 商户名称
  send_name: "猴赛雷"
  # 付款金额 单位分
  total_amount: "1"
  # 红包发放总人数
  total_num: 1
  # 红包祝福语
  wishing: "我感谢你哦"
  # Ip地址
  client_ip: 192.168.0.1
  # 活动名称
  act_name: "答题发红包"
  # 备注
  remark: "你可真聪明哦"

---
##### prod 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


